annotations:
  artifacthub.io/changes: |
    - "fix(Traefik Proxy): support uppercase letters in entrypoint names"
    - "feat(deps): update traefik docker tag to v3.3.2"
    - "feat(Traefik Hub): add OAS validateRequestMethodAndPath - CRDs update"
    - "chore(release): publish v34.1.0 and CRDs v1.2.0"
apiVersion: v2
appVersion: v3.3.2
description: A Traefik based Kubernetes ingress controller
home: https://traefik.io/
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
keywords:
- traefik
- ingress
- networking
kubeVersion: '>=1.22.0-0'
maintainers:
- email: michel.loiseleur@traefik.io
  name: mloiseleur
- email: charlie.haley@traefik.io
  name: charlie-haley
- email: remi.buisson@traefik.io
  name: darkweaver87
- name: jnoordsij
name: traefik
sources:
- https://github.com/traefik/traefik
- https://github.com/traefik/traefik-helm-chart
type: application
version: 34.1.0
